### ISSUE TITLE
Exponentiation should have a different prioritisation for solidity version bellow `0.8.0`

### ISSUE THREAD

**Issue by Janther** [NomicFoundation/slang#1031]
originally Solidity's exponentiation had left associativity which was fixed at `0.8.0`.

If I set the compiler bellow `0.8.0` I expect the output of `a ** b ** c` to resemble the following:

```JSON
{
  "leftOperand": {
    "leftOperand": "a",
    "operator": "**",
    "rightOperand": "b"
  },
  "operator": "**",
  "rightOperand": "c"
}
```

Instead I the parser returns something like:

```JSON
{
  "leftOperand": "a",
  "operator": "**",
  "rightOperand": {
    "leftOperand": "b",
    "operator": "**",
    "rightOperand": "c"
  }
}
```

This is just a simplification of the actual result but it helps as a guide.

UPDATE:
With further testing `0.5.8` works as expected while `0.7.0` has this bug. Will need to investigate further to figure out in which versions this doesn't work properly.

**Comment by Xanewok** [comment]
@OmarTawfik this is probably correct:

We currently define the 0.6.0 as the version that changed this: https://github.com/NomicFoundation/slang/blob/0630345ae2d4098db67a54e14ce28ba41c01eb86/crates/solidity/inputs/language/src/definition.rs#L3359-L3374

However, looking at the commits upstream, it seems that 0.8.0 is only the version that changed the associativity itself: https://github.com/ethereum/solidity/commit/13e7012e1ec2d69f8af4432320553742ac4ba8ec.

What has changed in 0.6.0 are the type semantics, where the type of the base is used for the result, rather than the operand's: https://github.com/ethereum/solidity/commit/33f7f960cfa39f13aec802487dd0f18cefe99559.
