### ISSUE TITLE
Ensure error recovery does not misparse in the event of ambiguous syntax

### ISSUE THREAD

**Issue by OmarTawfik** [NomicFoundation/slang#861]
> even though a `NamedArgument` is required inside `{}`, it is matched successfully as a post-fix expression, and thus, failing for expecting the `try` body afterwards.

_Originally posted by @OmarTawfik in https://github.com/NomicFoundation/slang/pull/853#discussion_r1501403364_

**Comment by Xanewok** [comment]
@OmarTawfik this refers to the `Separated` parser of `NamedArguments` at (latest) https://github.com/NomicFoundation/slang/pull/853/files#diff-af454bb70b3f914baf6e383790278f8efd4f555a445ec8b915164e93d73cc1d1R3354, right?

**Comment by Xanewok** [comment]
Here's more context about the underlying issue:

It includes a delimited parser (`{` `NamedArguments` `}`) that recovers on the empty content at the nearest delimiter matching the current tree, so the parse returns "Match, but recovered" (includes `SKIPPED` nodes).

Now, since the expression parser will happily tack that recovered group onto the current accumulator, we end up with `a.b()` ++ `{}` (recovered).

Because this syntax is generally ambiguous and is explicitly disambiguated by `solc` with a token lookahead to check for at least a single item (Identifier followed by a colon), we can't really attempt recovering here from an empty match as this leads to the issue where we can recover past the point where another parser (`Block` here) should pick up, leading to a misparse.

We already have a notion of `RecoverFromNoMatch` for recovery that's currently always emitted for terminators; we should surface this to a DSL and allow the users to disable error recovery in the face of ambiguous syntax such as this.

**Comment by OmarTawfik** [comment]
@Xanewok fixed the title. Thanks!

**Comment by Xanewok** [comment]
Changed the title to better reflect the underlying issue and what we're trying to fix in the short/mid term here.
