### ISSUE TITLE
ebnf links broken for precedence expressions

### ISSUE THREAD

**Issue by OmarTawfik** [NomicFoundation/slang#917]
This is a bug in the rendered EBNF for `PrecedenceOperator` items. For example, if you look at `Expression` below, you will find it referring to other operators like `AssignmentExpression` and `ConditionalExpression`, but the page doesn't actually include the definition of these operators, so clicking on them fails to navigate to it. We need to make sure we include the definition of such operators into the rendered page:

https://nomicfoundation.github.io/slang/solidity-specification/05-expressions/01-base-expressions/

Code pointers:

- `crates/codegen/ebnf/src/model.rs` the model we build from the grammar.
- `crates/codegen/ebnf/src/builder.rs` is where we build the model.
- `crates/codegen/spec/src/generators/topic_page.rs` is where the model is converted into markdown snippets.

**Comment by 0xf333** [comment]
Hi @OmarTawfik , is it possible to have more context on this? I could give it a shot to take it off your plate since I'm noticing that you have been assigned a lot of tickets.

Secondly, are precedence expression documentation in `language-definition-v2.md` intentionally missing this repo related source code link(s)? [e.g](https://github.com/NomicFoundation/slang/blob/2d698ebe469110b85f539d6e0c75b503cd4ce57e/crates/solidity/inputs/language/src/definition.rs#L144)

**Comment by OmarTawfik** [comment]
Hi @0xf333

Apologies for missing your comment! and thank you so much for your interest in helping!
I have updated the issue with more information. Please let me know if you have any questions!
